Bugfix for survey species list
SoftwareCornwall/rockpool-bds pull request #14
Opened 2018-08-08 13:51 UTC by MrDrummer

2018-08-08 15:26 UTC, ArronSpeake commented on central_web_server/ui_files/survey.js
> +      })
semicolons for consistency

2018-08-08 15:29 UTC, ArronSpeake commented on central_web_server/handle_database.js
> +    {
oneline these for readability (only if you think that looks better)
ie:
```
{ "species_id": 1, },
{ "species_id": 3, },
{ "species_id": 6, },
{ "species_id": 7, }
```

2018-08-08 15:31 UTC, ArronSpeake commented on central_web_server/ui_files/survey.js
> +    let foundSpeciesObjects = [];
objects?
maybe `submittedSpecies` is a more understandable name?

2018-08-08 15:31 UTC, ghost requested changes
just some readability stuff

2018-08-09 10:36 UTC, byran requested changes

2018-08-09 10:36 UTC, byran commented on central_web_server/handle_database.js
> +getLocation();
Remove the two lines above as they will create things every time the script is imported

2018-08-09 10:36 UTC, byran commented on database/setup-database.sql
> +  location_id varchar(5) NOT NULL,
I think this wants to be an int, not a varchar as it's an index to the location table

2018-08-09 10:36 UTC, byran commented on database/setup-database.sql
> +  temperature tinyint NOT NULL,
I think this should be a float or double

2018-08-09 11:07 UTC, merged